spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    username: vhr_admin
#    password: vhr_admin
    username: root
    password: shishi!159773
    url: jdbc:mysql://39.106.194.73:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    username: admin
    password: admin
    host: 39.106.194.73
#    publisher-confirms: true
    publisher-returns: true
    publisher-confirm-type:
  redis:
    host: 39.106.194.73
    database: 0
    port: 6379
    password: vhr_admin
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://127.0.0.1/